/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI - version 0.1.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'auth.token_auth_token_post': ['POST', '/auth/token'],
  'auth.register_auth_register_post': ['POST', '/auth/register'],
  'user.get_user_user__get': ['GET', '/user/'],
  'user.update_user_user__put': ['PUT', '/user/'],
  'user.delete_user_user__id__delete': ['DELETE', '/user/{id}'],
  'file.get_file_file__get': ['GET', '/file/'],
  'file.create_file_file__post': ['POST', '/file/'],
  'file.delete_file_file__delete': ['DELETE', '/file/'],
  'file.get_file_content_by_id_file__id__get': ['GET', '/file/{id}'],
  'file.update_file_file_update_content_put': ['PUT', '/file/update-content'],
  'file.move_file_file_move_to_put': ['PUT', '/file/move-to']
};
