/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI - version 0.1.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.stream_endpoint_stream_post': ['POST', '/stream'],
  'user.update_user_user__put': ['PUT', '/user/'],
  'user.delete_user_user__id__delete': ['DELETE', '/user/{id}'],
  'auth.login_auth_login_post': ['POST', '/auth/login'],
  'auth.register_auth_register_post': ['POST', '/auth/register']
};
